<?php
// Variables
return [
    "creatorName"         => "Feeri Dashboard",
    "creatorUrl"          => "https://feeri.io",
    "templateName"        => "FeeriLogis",
    "templateSuffix"      => "Feeri Dashboard",
    "templateVersion"     => "2.0.0",
    "templateFree"        => false,
    "templateDescription" => "Feeri Dashboard",
    "templateKeyword"     => "Feeri Dashboard",
    "licenseUrl"          => "https://feeri.io",
    "livePreview"         => "https://feeri.io",
    "productPage"         => "https://feeri.io",
    "support"             => "https://feeri.io",
    "moreThemes"          => "https://feeri.io",
    "documentation"       => "https://feeri.io",
    "generator"           => "",
    "changelog"           => "https://feeri.io",
    "repository"          => "https://feeri.io",
    "gitRepo"             => "FEERI",
    "gitRepoAccess"       => "vuexy-html-admin-template",
    "githubFreeUrl"       => "https://feeri.io",
    "facebookUrl"         => "https://feeri.io",
    "twitterUrl"          => "https://feeri.io",
    "githubUrl"           => "https://feeri.io",
    "dribbbleUrl"         => "https://feeri.io",
    "instagramUrl"        => "https://feeri.io",
];
